
# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
# Datasource
  datasource:
  # Use file directly
  # url: jdbc:h2:file:~/testdb
    # Use in memory db
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  liquibase:
    change-log: classpath:db/liquibase-changeLog.xml